%YAML:1.0


landmark_len: 200

dt: 0.02

keyframe_rate_ratio: 5

trajectory:
  r: 5.5 # circle radius x-y plane
  w: .46 # angular velocity, roughly 13.65 sec for a round
  r_z: 0.25
  w_z: 1.748
  z_h: 0.0 # height of the uav

imu_param:
  sigma_g_c: 1.0e-4 # gyro noise density [rad/s/sqrt(Hz)]
  sigma_a_c: 1.0e-3 # accelerometer noise density [m/s^2/sqrt(Hz)]


landmark_generation:
  box_xy: 2.0 # box offset from the circle
  box_z: 1 # box offset from uav height
  
landmark_init_noise: 0.01

camera:
  T_bc:
    [ 0.0, 0.0, 1.0, 0.0,
      0.0, 1.0, 0.0, 0.0,
     -1.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 1.0]
  image_dimension: [500, 1000]
  focal_length: [500.0, 500.0]
  principal_point: [0.0, 0.0]
  observation_noise: 0.0025
